### ISSUE TITLE
Canvas Teacher is not found 

### ISSUE THREAD

**Issue by rmlzy** [ReactNativeNews/React-Native-Apps#114]
Hi,
I noticed that the [Canvas Teacher](https://github.com/instructure/instructure-ios/tree/master/rn/Teacher) was invalid. Should it be removed?

Thanks.

**Comment by GantMan** [comment]
Yes, PR welcome!

**Comment by rmlzy** [comment]
@GantMan I submitted a PR, Please consider whether to accept it or not. Thank you.
