### ISSUE TITLE
Top page link "https://infinite.red/react-native" is 404 not found

### ISSUE THREAD

**Issue by shoken0x** [ReactNativeNews/React-Native-Apps#135]
This link "https://infinite.red/react-native" is 404 not found. Maybe https://infinite.red/technologies/react-native is correct?

![Screen Shot 2020-05-31 at 17 39 28](https://user-images.githubusercontent.com/475449/83348250-c1670500-a365-11ea-94ae-99bd0f722e1f.png)

**Comment by GantMan** [comment]
Thanks for finding this!   We had a site update and lost a few pages.

**Comment by GantMan** [comment]
fixed!

**Comment by shoken0x** [comment]
@GantMan Thanks ! 😀
