### ISSUE TITLE
Group apps somehow

### ISSUE THREAD

**Issue by brentvatne** [ReactNativeNews/React-Native-Apps#4]
Easiest one is games / apps. Maybe more

**Comment by alexakasanjeev** [comment]
@GantMan Hi, I would like to change the layout of the apps are listed and change it to Table Layout for easy viewing like this, should I go forward, (if yes which other column you think should be here beside this or should not be here)

| Title        | Description           | React Native Version  | Links |
| ----------- |:------------------------:|:-----------------------------:| -------:|
| [QRCode Reader and Generator](https://github.com/insiderdev/qrcode)| Mobile app for scanning and generating different types of QR Codes. | 0.59 | [iTunes Store](https://itunes.apple.com/us/app/id1445350234) [Google Play Store](https://play.google.com/store/apps/details?id=io.insider.apps.qr) |
|[Movie Swiper](https://github.com/azhavrid/movie-swiper)| Unofficial client for movie service | 0.58 | - |

**Comment by GantMan** [comment]
Looks great!  Please PR!

**Comment by alexakasanjeev** [comment]
Hello @GantMan there are some links, which no longer works, shall I remove them or keep them for example

QRCode Reader and Generator has link https://play.google.com/store/apps/details?id=io.insider.qrcode which no longer works, should I remove it keep it?

**Comment by GantMan** [comment]
please delete anything that doesn't work.  I appreciate it!

**Comment by alexakasanjeev** [comment]
hi @GantMan There are few repos, which has been archived and no longer maintained
for example
- [Chain React Conf](https://github.com/infinitered/ChainReactApp)
- [Boost Note](https://github.com/BoostIO/boostnote-mobile)

Should these entries be removed or kept?

**Comment by alexakasanjeev** [comment]
hi @GantMan I have opened a Pull request with new changes, please review
