### ISSUE TITLE
Run with latest react-native version

### ISSUE THREAD

**Issue by idnael** [ReactNativeNews/React-Native-Apps#47]
I tried some of the Exponent apps from the list and can't run then. Must be related with latest react-native version. Couldn't fix it yet. 
Please see this question. 
https://stackoverflow.com/questions/46713938/starting-react-native-app?noredirect=1#comment80375432_46713938

Any more recent src code ?

**Comment by GantMan** [comment]
Lots of exponent apps for sure.  Can you send a PR removing the ones that don't work?

Check this one out:
https://blog.expo.io/introducing-expo-ar-mobile-augmented-reality-with-javascript-powered-by-arkit-b0d5a02ff23
