### ISSUE TITLE
Sort by popularity

### ISSUE THREAD

**Issue by friederbluemle** [ReactNativeNews/React-Native-Apps#93]
It would be incredibly helpful to better understand how popular these individual projects are, without clicking through a long list of repos. Many entries are only used by a few users, or are outdated. Also see #3 

The number of **GitHub stars** would be a strong indicator, and the last update (last commit date) could also be useful.

**Comment by GantMan** [comment]
I'm down!  Would you be interested in writing a script that looks up their stars and updates the sort accordingly?   Good contributor project imo.
